name: Build Snapmaker Orca Spoolman Edition

on:
  workflow_dispatch:
  push:
    branches:
      - spoolman-profile-link

concurrency:
  group: spoolman-profile-link-windows
  cancel-in-progress: true

jobs:
  windows:
    name: Windows x64
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: windows-2022
      arch: x64
      build-deps-only: false
    secrets: inherit
